src/blogger/urls.py
from django.urls import include, path
from blogger.views import blogger, member, legendary


# app_name = 'blogger'
urlpatterns = [
    path('', blogger.home, name='home'),
    path('posts/', legendary.PostListView.as_view(), name='post'),
    path('post/<int:pk>', legendary.PostDetailView.as_view(), name='detail-post'),

    path('member/', include(([
        path('', member.details, name='member-detail'),
    ], 'blogger'), namespace='member')),

    path('legendary/', include(([

        path('', legendary.dashboard, name='legendary-dashboard'),
        path('api/', legendary.get_data),

        path('post/new', legendary.PostCreateView.as_view(), name='create-post'),
        path('post/<int:pk>/update/', legendary.PostUpdateView.as_view(), name='update-post'),
        path('post/<int:pk>/delete/', legendary.PostDeleteView.as_view(), name='delete-post'),

    ], 'blogger'), namespace='legendary')),

]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('secret/', admin.site.urls),
    path('', include('blogger.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),


    path('user/', include('users.urls')),
    path('reset_password/', auth_views.PasswordResetView.as_view(), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_complete"),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/users/urls.py
from django.urls import path
from users import views


app_name = 'users'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    path('profile/', views.profile, name='profile'),
]

src/blogger/models.py
from django.db import models
from django.utils import timezone
from users.models import User
from django.urls import reverse

from django_ckeditor_5.fields import CKEditor5Field


class Post(models.Model):

    title = models.CharField(max_length=100)
    content = CKEditor5Field(config_name='extends', blank=True, null=True)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail-post', kwargs={'pk': self.pk})


class Comment(models.Model):

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = CKEditor5Field(config_name='extends', blank=True, null=True)
    release_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.post.title}-{self.user.username}'

src/blogger/forms.py
from django import forms
from blogger.models import Post, Comment

class CreatePostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'content']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

src/blogger/views/blogger.py
from django.shortcuts import render, redirect


def home(request):

    if request.user.is_authenticated:
        if request.user.is_super_blogger:
            return redirect('legendary:legendary-dashboard')
        else:
            return redirect('member:member-detail')
    else:
        return redirect('users:signin')

src/blogger/views/legendary.py
from django.shortcuts import render, redirect,get_object_or_404
from django.http import JsonResponse

from blogger.models import Post, Comment
from users.models import User
from django.db.models import Q

from blogger.forms import CreatePostForm, CommentForm

from users.decorators import super_blogger_required
from django.contrib.auth.decorators import login_required

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from django.views.generic.edit import FormMixin


@login_required()
@super_blogger_required()
def dashboard(request):
    posts = Post.objects.all().filter(author=request.user.id)
    posts_count = posts.count()
    return render(request, 'blogger/legendary/dashboard.html', locals())


class PostListView(ListView):

    model = Post
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 2

    def get(self, request, *args, **kwargs):
        post_contains = request.GET.get('post_search')

        if post_contains:
            self.object = Post.objects.filter(Q(title=post_contains)).distinct()
        else:
            self.object = Post.objects.all()

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = self.object
        return context


class PostDetailView(LoginRequiredMixin, FormMixin, DetailView):

    template_name = 'blogger/legendary/post_detail.html'
    model = Post
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['form'] = CommentForm(initial={'post': self.object})
        context['comments'] = Comment.objects.filter(post=kwargs['object'].id).order_by('id')
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            instance_post = get_object_or_404(Post, id=kwargs['pk'])
            content_data = request.POST.get('content')
            comment = Comment.objects.create(post=instance_post, user=request.user, content=content_data)
            comment.save()
            return redirect('detail-post', pk=kwargs['pk'])
        else:
            return self.form_invalid(form)



class PostCreateView(LoginRequiredMixin, CreateView):

    model = Post
    template_name = 'blogger/legendary/create_post.html'
    form_class = CreatePostForm
    success_url = reverse_lazy('legendary:legendary-dashboard')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):

    model = Post
    template_name = 'blogger/legendary/update_post.html'
    fields = ['title', 'content']
    success_url = reverse_lazy('legendary:legendary-dashboard')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        else:
            return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):

    model = Post
    template_name = 'blogger/legendary/post_confirm_delete.html'
    success_url = reverse_lazy('legendary:legendary-dashboard')

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        else:
            return False

#-------------------------------------[ CHART-API-DASHBOARD ]-----------------------------------------------------------------#

def get_data(request, *args, **kwargs):
    posts_name = []
    user = User.objects.get(username='kingkong')
    posts = user.post_set.all()

    for post in posts:
        comments = post.comment_set.count()
        posts_name.append({
            'post': post.title,
            'comments': comments
        })

    return JsonResponse(posts_name, safe=False)



#-------------------------------------[ POST-COMMENT ]-----------------------------------------------------------------#


# class CommentCreateView(LoginRequiredMixin, CreateView):
#
#     model = Comment
#     form_class = CommentForm
#     success_url = reverse_lazy('legendary:legendary-dashboard')
#
#     def form_valid(self, form):
#         # form.instance.author = self.request.user
#         #
#         # comment = Comment.objects.create(episode=episode, user=request.user, content=content)
#         # comment.save()
#         return super().form_valid(form)

src/blogger/views/member.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from users.decorators import super_blogger_required

@login_required
def details(request):
    return HttpResponse('hello world ')

src/blogger/templates/blogger/legendary/create_post.html
{% extends 'layout/layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
<hr><br><br>

<div class="container">
  <form action="{% url 'legendary:create-post' %}" method="post">
    {% csrf_token %}
    {{ form.media }}

    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Blog Post</legend>
      {{ form|crispy }}
    </fieldset>
    <div class="">
      <button class="btn btn-primary" type="submit">Post</button>
    </div>
  </form>
</div>

{% endblock %}

src/blogger/templates/blogger/legendary/dashboard.html
{% extends 'layout/layout.html' %}
{% load static %}

{% block content %}
<hr><br><br>

<div class="container">
  {% include 'blogger/legendary/stats.html' %}

  <div class="row">

    <div class="col-md">
      <h5 class="card text-uppercase text-center">post</h5>

      <div class="card card-body">
        <a href="{% url 'legendary:create-post' %}" class="btn btn-primary btn-sm btn-block">create post</a>

        <table class="table">
          <thead>
            <tr>
                <th class="text-center">#</th>
                <th class="text-right">Title</th>
                <th class="text-right">Date posted</th>
                <th class="text-right">author</th>
                <th class="text-right">Actions</th>
            </tr>
          </thead>
          <tbody>
              {% for post in posts %}
                <tr>
                  <td class="text-center">{{ post.id }}</td>
                  <td class="text-right">{{ post.title }}</td>
                  <td class="text-right">{{ post.date_posted|date:"F d, Y" }}</td>
                  <td class="text-right">{{ post.author }}</td>
                  <td class="td-actions text-right">
                    <a type="button" rel="tooltip" class="btn btn-info btn-icon btn-sm btn-simple" data-original-title="" title="" href="{% url 'detail-post' post.id %}">
                      <i class="ni ni-circle-08 pt-1"></i>
                    </a>
                    <a type="button" rel="tooltip" class="btn btn-success btn-icon btn-sm btn-simple" data-original-title="" title="" href="{% url 'legendary:update-post' post.id %}">
                      <i class="ni ni-settings-gear-65 pt-1"></i>
                    </a>
                    <a type="button" rel="tooltip" class="btn btn-danger btn-icon btn-sm btn-simple" data-original-title="" title="" href="{% url 'legendary:delete-post' post.id %}">
                      <i class="ni ni-fat-remove pt-1"></i>
                    </a>
                  </td>
                </tr>
              {% endfor %}

          </tbody>
        </table>

      </div>
    </div>

  </div>

</div>

{% endblock %}

src/blogger/templates/blogger/legendary/post_confirm_delete.html
{% extends 'layout/layout.html' %}
{% block content %}
<hr><br><br>
<div class="container">
  <div class="content-section">
      <form method="POST">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Delete Post</legend>
              <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
          </fieldset>
          <div class="form-group">
              <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
              <a class="btn btn-outline-secondary" href="{% url 'detail-post' object.id %}">Cancel</a>
          </div>
      </form>
  </div>
</div>


{% endblock %}

src/blogger/templates/blogger/legendary/post_detail.html
{% extends 'layout/layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
<hr><br><br>
<div class="container">

  <div class="row">
    <div class="col-sm-8">
      {{ object.content|safe }}

      <hr>
        {% if comments %}
        <h2 class="heading mb-2">{{ comments.count }} Comment{{ comments|pluralize }}</h2>
        {% else %}
        <h2 class="heading mb-2">comment</h2>
        {% endif %}


        {% for comment in comments %}
        {% if comment.user.is_super_blogger %}
          <blockquote class="lead card border-warning p-2">
            <p class="display-4 mb-0 ">{{ comment.content|safe }}</p>
            <footer class="blockquote-footer">by <cite title="">{{ comment.user|capfirst }}</cite> </footer>
          </blockquote>
        {% else %}
        <blockquote class="lead p-2">
          <p class="display-4 mb-0 ">{{ comment.content|safe }}</p>
          <footer class="blockquote-footer">by <cite title="">{{ comment.user|capfirst }}</cite> </footer>
        </blockquote>
        {% endif %}
        {% endfor %}

        <form action="{% url 'detail-post' object.id %}" method="POST">
          {% csrf_token %}
          {{ form.media }}
          {{ form|crispy }}
          <button type="submit" class="btn btn-success btn-sm mt-2">Enter</button>
        </form>

    </div>
    <div class="col-sm">


      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="{{ post.author.profile.picture.url }}" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">{{ object.author }} {{ user.picture.url }}</h5>
        </div>
      </div>

    </div>
  </div>
</div>

{% endblock %}

src/blogger/templates/blogger/legendary/stats.html
<div class="row">
	<div class="col-md">
		<div class="col-md">
			<div class="card border-dark mb-3 text-center text-white  mb-3" id="total-orders">
			  	<div class="card-header">
			  		<h5 class="card-title">Total Posts</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{ posts_count }}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col-md">
		<div class="col-md">
			<div class="card border-dark mb-3 text-center text-white  mb-3" id="orders-delivered">
			  	<div class="card-header">
			  		<h5 class="card-title">Total Comments</h5>
			  	</div>
			  	<div class="card-body">
						<canvas id="myChart" width="400"></canvas>

			  	</div>
			</div>
		</div>
	</div>


</div>

src/blogger/templates/blogger/legendary/update_post.html
{% extends 'layout/layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
<hr><br><br>
<div class="container">
  <form action="{% url 'legendary:update-post' object.id %}" method="post">
    {% csrf_token %}
    {{ form.media }}

    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Blog Post</legend>
      {{ form|crispy }}
    </fieldset>
    <div class="">
      <button class="btn btn-primary" type="submit">Post</button>
    </div>
  </form>
</div>

{% endblock %}