src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('secret/', admin.site.urls),
    path('', include('blogger.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),


    path('user/', include('users.urls')),
    path('reset_password/', auth_views.PasswordResetView.as_view(), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_complete"),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/users/urls.py
from django.urls import path
from users import views


app_name = 'users'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    path('profile/', views.profile, name='profile'),
]

src/templates/layout/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

  <head>
    <meta charset="utf-8">
    <title>
      {% block head_title_base %}{% if SITE_NAME %}{{ SITE_NAME }} | {% endif %}{% block head_title %}{% endblock %}{% endblock %}
    </title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800" rel="stylesheet">
    <link href="{% static '/assets/vendor/nucleo/css/nucleo-svg.css' %}" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link type="text/css" href="{% static '/assets/vendor/nucleo/css/nucleo.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static '/assets/css/argon.min.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static '/layout/css/main.css' %}" rel="stylesheet">
    {% block style %}{% endblock %}

  </head>

  <body>

    <nav class='navbarb mb-5'>

      <a class='logo' href='{% url 'home' %}'>
        <div id='particles'></div>
        <h1>
          Visibily
          <sup>beta</sup>
        </h1>
      </a>

      <div class='controls'>
        <a href='{% url 'post' %}'>
          <span>posts</span>
        </a>
        {% if request.user.is_authenticated %}
          <a href='{% url 'users:profile' %}'>
            <span>profile</span>
          </a>
          <a href='{% url 'users:signout' %}'>
            <span>signout</span>
          </a>
        {% else %}
          <a href='{% url 'users:signup' %}'>
            <span>signup</span>
          </a>
          <a href='{% url 'users:signin' %}'>
            <span>signin</span>
          </a>
        {% endif %}
      </div>
    </nav>

    {% block content %}{% endblock %}
    <hr><br><br>

    <script src="{% static '/assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static '/assets/vendor/popper/popper.min.js' %}"></script>
    <script src="{% static '/assets/vendor/bootstrap/bootstrap.min.js' %}"></script>

    <script src="{% static '/assets/js/argon.min.js' %}"></script>
    <script src="{% static '/layout/scripts/main.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>

    {% block scripts %}{% endblock %}
  </body>
</html>